# A serverless service that sends out emails via Mailgun

service:
  name: email
  description: 'A service that sends out emails.'

custom:
  eventGatewayUrl: "http://localhost:4000"
  eventGatewayConfigUrl: "http://localhost:4001"

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  environment:
    EVENT_GATEWAY_URL: ${self:custom.eventGatewayUrl}
    EVENT_GATEWAY_CONFIG_URL: ${self:custom.eventGatewayConfigUrl}

functions:
  sendWelcomeEmail:
    handler: handler.sendWelcomeEmail
    events:
      - user.created
